// include file used only for code generating .c files to open output file

#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include "../emulator/inc/stdstuff.h"

FILE *ofile;

void outf(char *fmt,...)
{
va_list args;

	va_start(args,fmt);
	vfprintf(ofile,fmt,args);
	va_end(args);
}

#define openit(argc,argv) open_outfile(argc,argv,__FILE__)

void open_outfile(int argc, char **argv,char *file)
{
char *outname = "no file name";

	if(argc > 1)
		outname = argv[1];
	if(NULL == (ofile = fopen(outname, "w")))
	{
		printf("can't open \"%s\" for output.\n", outname);
		exit(1);
	}
	outf("; generated by %s \n\n\n",file);
}

#define closeit()\
	outf("\n\n; end %s generated code\n",__FILE__);fclose(ofile)

char _fmtequ[] = "%s equ 0%xh\n";

#define name_equ(name) outf(_fmtequ,#name,name)
#define soset(struc,name,f) outf(_fmtequ,#name,OFFSET(struc,f))
#define sosetpfix(struc,prefix,f) outf(_fmtequ,#prefix #f,OFFSET(struc,f))

#define sfoset(fmt,struc,name,f) outf(fmt,#name,OFFSET(struc,f))
void _extn(char *name)
{
	outf("    EXTRN %s_ :BYTE\n",name);
}
#define Extern(n) _extn(#n);
void _extndata(char *name)
{
	outf("    EXTRN _%s :BYTE\n",name);
}
#define Extdata(n) _extndata(#n);

#define DOTIFRIEND friend int main(int argc,char **argv);
#undef stdin 
#undef stdout 
#undef stderr 
