/******************************************************************************
 File: mkbio.h

 By: David Schwartz

 Date: August 1994

 (C) Williams Entertainment

 Mortal Kombat III bio case header
******************************************************************************/

#ifndef __mk_bio_h__
#define __mk_bio_h__

/*
 *	DEFINITIONS
 */
#define RED_GRAD	0
#define GREEN_GRAD	1
#define BLUE_GRAD	2

/*
 *	RAM
 */

/*
 *	PROTOTYPES
 */
void mk3_bio(void);
void mk3_gradient(WORD pa0);

/*
 *	MACROS
 */

#endif	/* __mk_bio_h__ */
